const data = [
  {
    image: "/main/umn_main.png",
    title: "UMN",
    source: "",
    website: "https://umn.vercel.app",
    stack: [
      { tailwind: true },
      { firebase: true },
      { redux: true },
      { next: true },
      { nest: true },
      { framer: true },
    ],
    images: [
      "/main/umn_main.png",
      "/work/umn/1.png",
      "/work/umn/2.png",
      "/work/umn/3.png",
      "/work/umn/4.png",
    ],
  },
  {
    image: "/main/krauv_main.png",
    title: "KRAUV",
    source: "https://github.com/MusaMalikx/krauv",
    website: "https://krauv.vercel.app",
    stack: [
      { tailwind: true },
      { firebase: false },
      { redux: true },
      { react: true },
      { next: false },
      { nest: false },
    ],
    images: [
      "/main/krauv_main.png",
      "/work/krauv/1.png",
      "/work/krauv/2.png",
      "/work/krauv/3.png",
      "/work/krauv/4.png",
      "/work/krauv/5.png",
      "/work/krauv/6.png",
      "/work/krauv/7.png",
      "/work/krauv/8.png",
    ],
  },
  {
    image: "/main/port_main_2.png",
    title: "PORTFOLIO 2.0",
    source: "",
    website: "https://musa.vercel.app",
    stack: [{ next: true }, { chakra: true }, { framer: true }],
    images: [
      "/main/port_main_2.png",
      "/work/port2/1.png",
      "/work/port2/2.png",
      "/work/port2/3.png",
      "/work/port2/4.png",
      "/work/port2/5.png",
    ],
  },
  {
    image: "/main/netflix_main.png",
    title: "NETFLIX",
    website: "https://netflix-2-0.vercel.app",
    source: "https://github.com/MusaMalikx/Netflix-2.0",
    stack: [{ tailwind: true }, { next: true }],
    images: [
      "/main/netflix_main.png",
      "/work/netflix/1.png",
      "/work/netflix/2.png",
      "/work/netflix/3.png",
      "/work/netflix/4.png",
      "/work/netflix/5.png",
      "/work/netflix/6.png",
      "/work/netflix/7.png",
    ],
  },
  {
    image: "/main/nilami_main.png",
    title: "NILAMI",
    website: "https://nilami.vercel.app",
    source: "https://github.com/MusaMalikx/Nilami",
    stack: [{ firebase: true }, { react: true }],
    images: [
      "/main/nilami_main.png",
      "/work/nilami/1.png",
      "/work/nilami/2.png",
      "/work/nilami/3.png",
      "/work/nilami/4.png",
    ],
  },
  {
    image: "/main/dehaat_main.png",
    title: "DEHAAT",
    website: "https://dehaat-silk.vercel.app",
    source: "https://github.com/MusaMalikx/Dehaat",
    stack: [
      { tailwind: true },
      { next: true },
      { chakra: true },
      { framer: true },
    ],
    images: [
      "/main/dehaat_main.png",
      "/work/dehaat/1.png",
      "/work/dehaat/2.png",
      "/work/dehaat/3.png",
      "/work/dehaat/4.png",
    ],
  },
  {
    image: "/main/ieee_main.png",
    title: "IEEE",
    website: "https://ieee-sage.vercel.app",
    source: "https://github.com/MusaMalikx/IEEE",
    stack: [
      { tailwind: true },
      { next: true },
      { chakra: true },
      { framer: true },
    ],
    images: [
      "/main/ieee_main.png",
      "/work/ieee/1.png",
      "/work/ieee/2.png",
      "/work/ieee/3.png",
      "/work/ieee/4.png",
      "/work/ieee/5.png",
    ],
  },
  {
    image: "/main/amazon_main.png",
    title: "AMAZON",
    website: "https://amazon-wine-one.vercel.app",
    source: "https://github.com/MusaMalikx/Amazon",
    stack: [{ tailwind: true }, { next: true }, { redux: true }],
    images: [
      "/main/amazon_main.png",
      "/work/amazon/1.png",
      "/work/amazon/2.png",
      "/work/amazon/3.png",
      "/work/amazon/4.png",
    ],
  },
  {
    image: "/main/hulu_main.png",
    title: "HULU",
    website: "https://hulu-tau-gules.vercel.app/",
    source: "https://github.com/MusaMalikx/hulu",
    stack: [{ tailwind: true }, { next: true }],
    images: [
      "/main/hulu_main.png",
      "/work/hulu/1.png",
      "/work/hulu/2.png",
      "/work/hulu/3.png",
      "/work/hulu/4.png",
    ],
  },
  {
    image: "/main/port_main_1.png",
    title: "PORTFOLIO 1.0",
    website: "https://portfolio-1-1.vercel.app/",
    source: "https://github.com/MusaMalikx/portfolio",
    stack: [{ tailwind: true }, { next: true }, { redux: true }],
    images: [
      "/main/port_main_1.png",
      "/work/port1/1.png",
      "/work/port1/2.png",
      "/work/port1/3.png",
      "/work/port1/4.png",
    ],
  },
];

export default data;
